name: Build Containers

on:
- push

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push client image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: client
        file: ./client/Dockerfile
        push: true
        tags: latest

    - name: Build and push server image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: server
        file: ./server/Dockerfile
        push: true
        tags: latest