name: Build Frontend  # Defines the name of the GitHub Actions workflow.

# on:
#     push:
#         branches:
#             - develop  # Triggers the workflow on each push to the 'develop' branch.

jobs:
  build:
    name: Build  # Defines the name of the build job.
    runs-on: ubuntu-latest  # Specifies the operating system for the job.

    steps:
    - name: Checkout Repo  # Checks out the repository.
      uses: actions/checkout@v4

    - name: Create Node Environment  # Sets up Node.js environment.
      uses: actions/setup-node@v4
      with: 
        node-version: 22.x

    - name: Install Packages and Build Application  # Installs npm packages and builds the Vue.js application.
      run: |
        npm ci
        npm run build

    - name: Upload artifact  # Uploads the build artifact.
      uses: actions/upload-pages-artifact@v2